name: Build, Test, and Publish Library

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 18, 23]  # Define the Node.js versions to test on
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use the version from the matrix

      - name: Install dependencies
        run: npm ci  # Install dependencies from the lockfile

      - name: Build the library
        run: npm run build  # Assuming you have a build script in package.json

      - name: Run tests
        run: npm test  # Run your tests

  publish:
    runs-on: ubuntu-latest
    needs: test  # Ensure the tests are run first
    if: startsWith(github.ref, 'refs/tags/v')  # Only run this on new version tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use any version (this is just for publishing)

      - name: Install dependencies
        run: npm ci  # Install dependencies from the lockfile

      - name: Build the library
        run: npm run build  # Build your library

      - name: Publish to npm
        run: npm publish --access public  # Publish to npm

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure the token is set in GitHub Secrets
