name: Release - Test, Build, Publish

on:
  release:
    types: [created]  # Triggers when a new release is created

jobs:
  test_build_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 18, 23]  # Test on Node.js versions 14, 18, and 23

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use the Node.js version from the matrix

      - name: Install dependencies
        run: |
          npm ci  # Installs dependencies based on the lockfile (package-lock.json)

      - name: Build the library
        run: npm run build  # Runs your build script from package.json

      - name: Run tests
        run: npm test  # Runs your test command

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Make sure to set NPM_TOKEN as a secret in GitHub
        run: npm publish --access public  # Publishes the package to npm
