name: Build, Test, and Publish Library

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 18, 23]  # Define the Node.js versions to test on
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use the version from the matrix

      - name: Install dependencies
        run: npm install # Install dependencies from the lockfile

      - name: Build the library
        run: npm run build  # Assuming you have a build script in package.json

      - name: Run tests
        run: npm test  # Run your tests

  publish:
    runs-on: ubuntu-latest
    needs: test  # Ensure the tests are run first

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install  # Install dependencies from the lockfile

      - name: Build the library
        run: npm run build  # Build your library

      - name: Publish to npm
        run: npm publish --access public  # Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure the token is set in GitHub Secrets
